### PR TITLE
Adding Contribution.md file 

### PR DESCRIPTION
**Pull request by ManasBhilare**
Thanks for such a wonderful oppurtunity!
If any changes are to be made please let me know.

### CODE REVIEW

**Comment by Drit-team** [comment]
Hi dear @Manas146, 
You provided an `.docx` file, please provide an `.md` (Markdown) file please.

**Comment by ManasBhilare** [comment]
@Drit-team oh sorry!
Did the changes.

**Comment by ManasBhilare** [comment]
@Drit-team can you please check PRs were incorrectly flagged as spam/invalid.

**Comment by ManasBhilare** [comment]
whereas the PR got merged succesfully!

**Comment by taha-ghadirian** [comment]
> @Drit-team can you please check PRs were incorrectly flagged as spam/invalid.

Hello @Manas146, #4 Accepted and flagged with `Hacktoberfest-accepted`. #3 Is closed and it's not valid for hacktoberfest. 
You created #4 for fixing #3 and then closed this.

**Comment by ManasBhilare** [comment]
oh @taha-ghadirian....can you please remove the invalid/spam tag?

**Comment by taha-ghadirian** [comment]
> oh @taha-ghadirian....can you please remove the invalid/spam tag?

Yes of course, Thanks for contributing to our project 😀❤️✌️
Happy Hacktoberfest.

**Pull request closed without merging**
